### PR TITLE
Added threading

### PR DESCRIPTION
**Pull request by R4g3D**
I added threading to allow multiple nmap scans to run concurrently.
Nmap does not saturate a network connection, so in large scans, scanning 1 host at a time is inefficient.

### CODE REVIEW

**Comment by R4g3D** [comment]
Code is broken, will submit again after fixing

**Comment by R4g3D** [comment]
Fixed the code, works fine now
I didn't pass through the required parameters to the threaded function.

**Comment by dogasantos** [comment]
Hey there! 
cool! Ill take a look asap 
Thank you!!

**Comment by R4g3D** [comment]
I've made a version that stays sequential by default, and if you add the `-t NUM` flag, enables threading with the specified number of threads.
If you prefer that, let me know and I will push before you accept the pull request.

**Comment by dogasantos** [comment]
> I've made a version that stays sequential by default, and if you add the `-t NUM` flag, enables threading with the specified number of threads. If you prefer that, let me know and I will push before you accept the pull request.

I think that would be nice, if you don't mind

**Comment by dogasantos** [comment]
I think sequential won't be needed

**Comment by R4g3D** [comment]
If sequential is not needed, you can accept the pull request then, the current version is working.

**Comment by dogasantos** [comment]
Just tested with 100 threads and got it broken on xml parsing results.
I'll test it again with different scenarios to make sure

**Comment by dogasantos** [comment]
just a snippet:

``` 
Exception in thread Exception in thread Thread-18:
Thread-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nmap/nmap.py", line 323, in analyse_nmap_xml_scan
  File "/usr/local/lib/python3.8/dist-packages/nmap/nmap.py", line 323, in analyse_nmap_xml_scan
    dom = ET.fromstring(self._nmap_last_output)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nmap/nmap.py", line 323, in analyse_nmap_xml_scan
    dom = ET.fromstring(self._nmap_last_output)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    dom = ET.fromstring(self._nmap_last_output)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 7, column 0
```

**Comment by R4g3D** [comment]
Honestly not sure what that error could be.
Not sure running 100 threads is a realistic scenario though.
It's more likely you would max out your threads to 2-3x your CPU count.
The error could have something to do with a limit on the total concurrent file read/writes possible.

**Comment by dogasantos** [comment]
I agree, but I'll have to address issue tickets in the future based on this
therefore, I have to test it
perhaps a max_thread via os.cpu_count
I'll try to find why the issue occurs first, it might be easy to fix

**Comment by dogasantos** [comment]
the error seems to occur in cases nmap is unable to produce results (no open ports found) 
toc-tou due to firewall or something
as this not seem to be a code-related, I'll merge your commit

really appreciated your contribution
thanks

**Comment by R4g3D** [comment]
Oh, that makes sense!
Awesome, glad to help, and happy to be a contributor.

**Pull request merged**
